/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionPanel: typeof import('./src/components/chat-components/actionPanel.vue')['default']
    ChatFrame: typeof import('./src/components/chat-components/chatFrame.vue')['default']
    ChatInterface: typeof import('./src/components/chat-components/chatInterface.vue')['default']
    ChatList: typeof import('./src/components/chat-components/chatList.vue')['default']
    'ChatList copy': typeof import('./src/components/chat-components/chatList copy.vue')['default']
    copy: typeof import('./src/components/chat-components/nav copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    FriendActionPanel: typeof import('./src/components/chat-components/actionPanel/friendActionPanel.vue')['default']
    FriendFrame: typeof import('./src/components/chat-components/friendFrame.vue')['default']
    FunctionPanel: typeof import('./src/components/chat-components/functionPanel.vue')['default']
    IdentifyCode: typeof import('./src/components/util-components/identifyCode.vue')['default']
    Nav: typeof import('./src/components/chat-components/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
